#!/bin/bash

export FLATPAK_ID=${FLATPAK_ID:-it.fabiodistasio.AntaresSQL}
export FEATURES="UseSkiaRenderer, WaylandWindowDecorations"
export TMPDIR="$XDG_RUNTIME_DIR/app/${FLATPAK_ID}"
declare -a FLAGS=(--enable-gpu-rasterization --enable-zero-copy --enable-gpu-compositing --enable-native-gpu-memory-buffers --enable-oop-rasterization --disable-gpu-blocklist --ozone-platform-hint=auto)

if [[ $XDG_SESSION_TYPE == "wayland" ]]
then
    if [[ -c /dev/nvidia0 ]]
    then
        echo "Using NVIDIA on Wayland, applying workaround"
        FLAGS+=(--disable-gpu-sandbox)
    fi

fi

FLAGS+=(--enable-features="${FEATURES}")
echo "Passing the following arguments to Electron:" "${FLAGS[@]}"
exec zypak-wrapper /app/Antares/antares "${FLAGS[@]}" "$@"
